--date and time function
--1. GETDATE(),getdate(),current_timestamp, systemdatetime()
--2. datename(),
--3. datediff()
--4. dateadd()

SELECT GETDATE() AS TODAY_DATE;
SELECT SYSDATETIME() AS TODAY_DATE;
SELECT CURRENT_TIMESTAMP AS TODAY_DATE;

SELECT DATENAME(MONTH,CURRENT_TIMESTAMP) AS 'MONTH';
SELECT DATENAME(YEAR,CURRENT_TIMESTAMP) AS 'YEAR';
SELECT DATENAME(HOUR,CURRENT_TIMESTAMP) AS 'HOUR';

SELECT DATEDIFF(YEAR,'JANUARY 6 1995',CURRENT_TIMESTAMP) 
AS "AGEBYYEAR";
SELECT DATEDIFF(MONTH,'JANUARY 6 1995',CURRENT_TIMESTAMP) 
AS "AGEBYMONTH";
SELECT DATEDIFF(YEAR,'JANUARY 26 2002','MAY 26 2023') 
AS "AGEBYYEAR";

SELECT DATEADD(YEAR,100,CURRENT_TIMESTAMP) AS "100YEARSFROMNOW";
SELECT DATEADD(MONTH,100,CURRENT_TIMESTAMP) AS "100MONTHSFROMNOW";
SELECT DATEADD(MONTH,10,CURRENT_TIMESTAMP) AS "10MONTHSFROMNOW";
