BEGIN TRY
	SELECT 100/5 AS 'DIVISION';
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE() AS 'ERROR MESSAGE';
END CATCH
GO

BEGIN TRY
	SELECT 100/0 AS 'DIVISION';
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE() AS 'ERROR MESSAGE',ERROR_LINE() AS 'ERROR LINE',
	ERROR_NUMBER() AS 'ERROR NUMBER', ERROR_PROCEDURE() AS 'ERROR PROCEDURE';
END CATCH
	SELECT ERROR_MESSAGE() AS 'ERROR MESSAGE',ERROR_LINE() AS 'ERROR LINE',
	ERROR_NUMBER() AS 'ERROR NUMBER', ERROR_PROCEDURE() AS 'ERROR PROCEDURE';
GO


BEGIN TRY
	SELECT 100/5 AS 'DIVISION';
END TRY
BEGIN CATCH

END CATCH
GO

BEGIN TRY
	SELECT 100/0 AS 'DIVISION';
END TRY
BEGIN CATCH

END CATCH
GO