SELECT GETDATE() AS 'CURRENT TIME';
GO
BEGIN 
	WAITFOR TIME '11:56:00'
	SELECT * FROM emp_info_bckp;
END
GO
SELECT GETDATE() AS 'CURRENT TIME';
GO


SELECT GETDATE() AS 'CURRENT TIME';
GO
BEGIN 
	WAITFOR DELAY '00:00:20'
	SELECT * FROM emp_info_bckp;
END
GO
SELECT GETDATE() AS 'CURRENT TIME';
GO
